### PR TITLE
Ebook pub

### PR DESCRIPTION
**Pull request by jnavila**
Not yet ready for merge

### CODE REVIEW

**Comment by jnavila** [comment]
Well, it passed! @andres-mancera Would you like to review the changes before the merge?

**Comment by andres-mancera** [comment]
Thanks @jnavila !  So you want me to go over the 489 changed files, review them and bless this merge?  😆   It'll be probably easier to merge and then go over the book and fix any issues at that point.  What do you think?

**Comment by jnavila** [comment]
Well, most of the changes are only cross-ref updates and removals of remainings of conflicts marks. That's mainly for what's left that I'm not sure of. I guess we can merge.

**Comment by jnavila** [comment]
The book is built only on tags. Tags are automatically created on master only.
Books are available at https://github.com/progit/progit2-es/releases and the url will be daily updated on git-scm.com.

**Comment by andres-mancera** [comment]
If I remember correctly, the book that was generated by the old build process contained a page that basically came directly from the [contributors](https://github.com/progit/progit2-es/blob/master/book/contributors.asc) file.  I no longer see that as part of the new book.  Any idea what happened?  IMO, having the names of the translators as part o the book was a nice token of appreciation.

**Comment by jnavila** [comment]
It can still be added.

**Comment by jnavila** [comment]
The trick here is that it has to be extracted from the present repository and won't reflect the contributors to the original book.

**Comment by jnavila** [comment]
The list is generated automatically now. You can modify the people appearing by changing the `.mailmap` file.

**Pull request merged**
